// <auto-generated />
namespace ConsoleApplicationEx_Aula4.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InicioProjeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicioProjeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201512082223442_InicioProjeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
